default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: babydog_development

test:
  <<: *default
  database: babydog_test

production:
  primary: &primary_production
    <<: *default
    database: babydog_production
    username: babydog
    password: <%= ENV["BABYDOG_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: babydog_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: babydog_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: babydog_production_cable
    migrations_paths: db/cable_migrate
